import type { Metadata } from "next";

import 'react-toastify/dist/ReactToastify.css'
import "./globals.css";
import Header from "@/components/Header";

import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import ModNav from "@/components/ModNav";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <ModNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
